insert into CRT_CUSTOMER (CST_ID, CST_PNR, CST_CITY, CST_FLAT_NUBMER, CST_HOUSE_NUMBER, CST_POSTAL_CODE, CST_STREET, CST_EMAIL, CST_FIRST_NAME, CST_LAST_NAME) values (1, '2001', 'Warsaw', '1', '2', '32-123', 'Main', 'john@noinc.com.acme.pl', 'John', 'Doe');
insert into CRT_CUSTOMER (CST_ID, CST_PNR, CST_CITY, CST_FLAT_NUBMER, CST_HOUSE_NUMBER, CST_POSTAL_CODE, CST_STREET, CST_EMAIL, CST_FIRST_NAME, CST_LAST_NAME) values (2, '2002', 'Warsaw', '1', '2', '33-123', 'Main', 'jane@noinc.com.acme.pl', 'Jane', 'Doe');
insert into CRT_CUSTOMER (CST_ID, CST_PNR, CST_CITY, CST_FLAT_NUBMER, CST_HOUSE_NUMBER, CST_POSTAL_CODE, CST_STREET, CST_EMAIL, CST_FIRST_NAME, CST_LAST_NAME) values (3, '2003', 'Warsaw', '1', '2', '34-123', 'Main', 'jack@noinc.com.acme.pl', 'Jack', 'Doe');

insert into CRT_PHONE (PHN_ID, PHN_CUSTOMER_ID, PHN_CUSTOMER_PNR, PHN_PRIM_CUSTOMER_ID, PHN_PRIM_CUSTOMER_PNR, PHN_NUMBER, PHN_TYPE) values (1, 1, '2001', 1, '2001', '111-111-111', 'MOBILE');
insert into CRT_PHONE (PHN_ID, PHN_CUSTOMER_ID, PHN_CUSTOMER_PNR, PHN_NUMBER, PHN_TYPE) values (3, 2, '2002', '111-333-111', 'OFFICE');
insert into CRT_PHONE (PHN_ID, PHN_CUSTOMER_ID, PHN_CUSTOMER_PNR, PHN_NUMBER, PHN_TYPE) values (4, 3, '2003', '111-333-111', 'MOBILE');

insert into CRT_PRODUCT (PRD_ID, PRD_NAME) values (1, 'Laptop');
insert into CRT_PRODUCT (PRD_ID, PRD_NAME) values (2, 'WIFI Network card');
insert into CRT_PRODUCT (PRD_ID, PRD_NAME) values (3, 'Memory Card');
insert into CRT_PRODUCT (PRD_ID, PRD_NAME) values (4, 'HDMI Cable');

insert into CRT_ORDER (ORD_ID, ORD_CUSTOMER_ID, ORD_CUSTOMER_PNR, ORD_ORDERED_ON) values (1, 1, '2001', CURRENT_TIMESTAMP());
insert into CRT_ORDER (ORD_ID, ORD_CUSTOMER_ID, ORD_CUSTOMER_PNR, ORD_ORDERED_ON) values (2, 3, '2003', CURRENT_TIMESTAMP());
insert into CRT_ORDER (ORD_ID, ORD_CUSTOMER_ID, ORD_CUSTOMER_PNR, ORD_ORDERED_ON) values (3, 3, '2003', CURRENT_TIMESTAMP());
insert into CRT_ORDER (ORD_ID, ORD_CUSTOMER_ID, ORD_CUSTOMER_PNR, ORD_ORDERED_ON) values (4, 3, '2003', CURRENT_TIMESTAMP());

insert into CRT_ORDER_ITEM (ORI_ID, ORI_ORDER, ORI_PRODUCT, ORI_QUANTITY) values (1, 1, 1, 1);
insert into CRT_ORDER_ITEM (ORI_ID, ORI_ORDER, ORI_PRODUCT, ORI_QUANTITY) values (2, 1, 2, 1);
insert into CRT_ORDER_ITEM (ORI_ID, ORI_ORDER, ORI_PRODUCT, ORI_QUANTITY) values (3, 2, 3, 1);
insert into CRT_ORDER_ITEM (ORI_ID, ORI_ORDER, ORI_PRODUCT, ORI_QUANTITY) values (4, 2, 4, 1);
insert into CRT_ORDER_ITEM (ORI_ID, ORI_ORDER, ORI_PRODUCT, ORI_QUANTITY) values (5, 3, 3, 3);
insert into CRT_ORDER_ITEM (ORI_ID, ORI_ORDER, ORI_PRODUCT, ORI_QUANTITY) values (6, 4, 3, 2);


